packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
catalog:
  eslint: ^9.39.1
  prettier: ^3.4.2
  typescript: ^5.9.2
catalogs:
  nestjs:
    '@nestjs/common': ^11.1.9
    '@nestjs/core': ^11.1.9
    '@nestjs/platform-express': ^11.1.9
    '@nestjs/config': ^4.0.2'
    '@nestjs/microservices': ^11.1.9
    '@nestjs/mapped-types': ^2.0.7
    '@nestjs/cli': ^11.0.0
    '@nestjs/schematics': ^11.0.0
    '@nestjs/testing': ^11.0.1'
    reflect-metadata: ^0.2.2'
