packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
catalog:
  eslint: ^9.39.1
  prettier: ^3.7.4
  typescript: ^5.9.2
  rxjs: ^7.8.1
catalogs:
  nestjs:
    '@nestjs/common': ^11.1.9
    '@nestjs/core': ^11.1.9
    '@nestjs/platform-express': ^11.1.9
    '@nestjs/config': ^4.0.2'
    '@nestjs/microservices': ^11.1.9
    '@nestjs/mapped-types': ^2.0.7
    '@nestjs/cli': ^11.0.0
    '@nestjs/schematics': ^11.0.0
    '@nestjs/testing': ^11.0.1'
    reflect-metadata: ^0.2.2'
  logger:
    'nest-winston': ^1.9.7
    'winston': ^3.15.0
    'winston-daily-rotate-file': ^5.0.0
