packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
catalog:
  eslint: ^9.39.1
  prettier: ^3.7.4
  typescript: ^5.9.2
  rxjs: ^7.8.1
catalogs:
  nestjs:
    '@nestjs/common': ^11.1.9
    '@nestjs/core': ^11.1.9
    '@nestjs/platform-express': ^11.1.9
    '@nestjs/config': ^4.0.2'
    '@nestjs/microservices': ^11.1.9
    '@nestjs/mapped-types': ^2.0.7
    '@nestjs/cli': ^11.0.0
    '@nestjs/schematics': ^11.0.0
    '@nestjs/testing': ^11.0.1'
    reflect-metadata: ^0.2.2'
    minio: ^8.0.5

  logger:
    'nest-winston': ^1.9.7
    'winston': ^3.15.0
    'winston-daily-rotate-file': ^5.0.0

  auth:
    '@nestjs/jwt': ^11.0.0
    '@nestjs/passport': ^11.0.5
    passport-jwt: ^4.0.1
    bcrypt: ^6.0.0
    '@types/bcrypt': ^6.0.0
    cookie-parser: ^1.4.7
    '@types/cookie-parser': ^1.4.7

  validation:
    zod: ^3.24.1
    nestjs-zod: ^4.3.1

  grpc:
    '@grpc/grpc-js': ^1.12.4
    '@grpc/proto-loader': ^0.7.15

  testing:
    jest: ^29.7.0'
    ts-jest: '^29.2.5'
    supertest: '^7.0.0'
    '@types/jest': '^29.5.14'
    '@types/supertest': '^6.0.2'

  dev:
    '@swc/cli': ^0.6.0
    '@swc/core': ^1.10.7
    ts-node: ^10.9.2
    ts-loader: ^9.5.2
    tsconfig-paths: ^4.2.0
    source-map-support: ^0.5.21
    env-cmd: '^10.1.0'

  prisma:
    '@prisma/client': ^6.6.0
    prisma: ^6.6.0'
